### ISSUE TITLE
Uncaught TypeError: Cannot read property 'template' of undefined 

### ISSUE THREAD

**Issue by nikolaygit** [nate-strauser/meteor-x-editable-bootstrap#11]
After installing and using the code in the README I get the error

```
Uncaught TypeError: Cannot read property 'template' of undefined 
```

in the file bootstrap-editable.js:4504

``` javascript
innerCss: $.fn.popover && $($.fn.popover.defaults.template).find('p').length ? '.popover-content p' : '.popover-content',
```

Environment: Meteor Release 0.6.6.3

**Comment by geekdevs** [comment]
For future googlers, I got the same problem when included wrong version of the library.
Make sure to use `x-editable/dist/bootstrap3-editable/js/bootstrap-editable.js` for bootstrap3.
