### ISSUE TITLE
wysihtml5 ... lists and link buttons not showing up

### ISSUE THREAD

**Issue by greenwolfe** [nate-strauser/meteor-x-editable-bootstrap#29]
I'm just testing this out before including it in a larger project.  I created a new meteor >1.0 project, added bootstrap3 and x-editable, and tested by making simple edits to main.html and main.js.  I know I have the right syntax for the wysihtml5 editor and the options for controlling the toolbar buttons, because I can hide the emphasis and font-styles.  As far as I can tell, lists and links should be showing up by default, but aren't.  Enabling them explicitly in the options does not work.  I can post details if that will help, but what I've done seems pretty basic.  As I don't see any posting about a similar bug, I could well just be missing something simple.  My apologies if so.

**Comment by greenwolfe** [comment]
I still intend to track this down, but have been distracted with another branch of my project.  At this point, I don't know when I'll get back to this.  Might a simple change from the icon-* class do, or will I have to look deeper into the code?

**Comment by brylie** [comment]
@digilord and/or @greenwolfe can you please post examples of how you use the wysihtml5 editor in Meteor? Also, can you please post a simple reproduction of this issue on Meteorpad? Thanks :-)

**Comment by greenwolfe** [comment]
Hi Brylie (?)  Nate (?),

Not sure who this is going to.  Anyway, just letting you know I have had 
to put this project on hold, but plan to get back to it starting next 
week.  I'll send you some examples then.  Thanks for taking note of the 
problem.

Matt

**Comment by greenwolfe** [comment]
I am now able to get back to this project and have created a github project with a minimal set of code to produce the bugs.  Further explortation shows the following:

The buttons for indent, outdent, ordered list, unordered list, link and insert image appear to be present, but they aren't rendered so are invisible.  indent, outdent, ordered list and unordered list appear to be functional if you can find the right place to click.  link and insert image appear not to be functional.  You click on the button and nothing happens.  I'm guessing a pop-up dialog is supposed to appear.

And additional error:  When text color is added, the button shows, but the text color only shows up after saving the edits. It does not show up in th editor itself.

https://github.com/greenwolfe/xeditableTest 

meteorpad is unavailable at my work, but I will get this up on meteor pad once I get home.

matt

**Comment by raza2022** [comment]
am having the same issue. any work around

**Comment by MegatronCupcakes** [comment]
I ran into the same and noticed the icons use fontawesome 3 classes.  Including a reference to the Font Awesome 3.2.1 css causes the missing buttons to display.
`<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">`

**Comment by brylie** [comment]
I added a PR that includes a FontAwesome package dependency.
